import { PrivyWrapper } from '@/provider'
import { type PropsWithChildren } from 'react'
import './globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body>
        <PrivyWrapper>{children}</PrivyWrapper>
      </body>
    </html>
  )
}
